<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>8ef4e533-db5e-424e-92dd-a491760c7fb7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IronForge.Shared\IronForge.Shared.csproj" />
  </ItemGroup>

</Project>
