<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IronForge.Shared\IronForge.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Agents\Persistence\" />
    <Folder Include="Auditing\Persistence\" />
    <Folder Include="Auth\Persistence\" />
    <Folder Include="McpClients\Models\" />
    <Folder Include="McpClients\Persistence\" />
    <Folder Include="Tenants\Persistence\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.13" />
    <PackageReference Include="Microsoft.Extensions.AI" Version="10.10.0" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.10.1" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.12" />
  </ItemGroup>

</Project>
