name: IronForge CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ironforge-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    name: Build IronForge

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'

      - name: Display .NET information
        run: dotnet --info

      - name: Restore
        run: dotnet restore ./IronForge.Server.slnx

      - name: Build
        run: dotnet build ./IronForge.Server.slnx --configuration Release --no-restore